--java.lang.AssertionError: ALTER TABLE t0 STATS_AUTO_RECALC 0, CHECKSUM 1, ENABLE KEYS, STATS_PERSISTENT DEFAULT, FORCE, COMPRESSION 'ZLIB', ALGORITHM INSTANT, DROP COLUMN c1;
--	at sqlancer.common.query.SQLQueryAdapter.checkException(SQLQueryAdapter.java:111)
--	at sqlancer.common.query.SQLQueryAdapter.execute(SQLQueryAdapter.java:93)
--	at sqlancer.Main$QueryManager.execute(Main.java:265)
--	at sqlancer.GlobalState.executeStatement(GlobalState.java:108)
--	at sqlancer.StatementExecutor.executeStatements(StatementExecutor.java:70)
--	at sqlancer.mysql.MySQLProvider.generateDatabase(MySQLProvider.java:152)
--	at sqlancer.mysql.MySQLProvider.generateDatabase(MySQLProvider.java:1)
--	at sqlancer.ProviderAdapter.generateAndTestDatabase(ProviderAdapter.java:52)
--	at sqlancer.Main$DBMSExecutor.run(Main.java:364)
--	at sqlancer.Main$2.run(Main.java:559)
--	at sqlancer.Main$2.runThread(Main.java:541)
--	at sqlancer.Main$2.run(Main.java:532)
--	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
--	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
--	at java.base/java.lang.Thread.run(Thread.java:829)
--Caused by: java.sql.SQLException: Unknown ALGORITHM 'INSTANT'
--	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:129)
--	at com.mysql.cj.jdbc.exceptions.SQLExceptionsMapping.translateException(SQLExceptionsMapping.java:122)
--	at com.mysql.cj.jdbc.StatementImpl.executeInternal(StatementImpl.java:763)
--	at com.mysql.cj.jdbc.StatementImpl.execute(StatementImpl.java:648)
--	at sqlancer.common.query.SQLQueryAdapter.execute(SQLQueryAdapter.java:87)
--	... 13 more
---- Time: 2023/06/01 18:30:17
-- Database: database55
-- Database version: 8.0.11
-- seed value: 1685637011045
DROP DATABASE IF EXISTS database55;
CREATE DATABASE database55;
USE database55;
CREATE TABLE IF NOT EXISTS t0(c0 BIGINT(245)  STORAGE DISK, c1 MEDIUMINT  PRIMARY KEY NOT NULL COLUMN_FORMAT DYNAMIC STORAGE MEMORY) CHECKSUM = 1, DELAY_KEY_WRITE = 1;
